refactor: remove parent task key
Substra/orchestrator pull request #112
Opened 2022-12-23 13:23 UTC by guilhem-barthes

## Companion PR

- https://github.com/Substra/substra-backend/pull/554

## Description

- Remove `compute_task_parents`:
 - in `ComputeTask`
 - in gRPC communication
 - remove `expanded_compute_tasks`

## How has this been tested?

CI

## Checklist

- [x] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

2022-12-23 13:30 UTC, guilhem-barthes commented
/e2e  --refs substra-backend=feat/remove-parent_task_key

2022-12-23 13:30 UTC, Owlfred commented
End to end tests: :hourglass_flowing_sand: **STARTING**

2023-01-02 13:59 UTC, guilhem-barthes commented
/e2e --refs substra-backend=feat/remove-parent_task_key

2023-01-02 13:59 UTC, Owlfred commented
End to end tests: :hourglass_flowing_sand: **STARTING**

2023-01-02 15:36 UTC, ThibaultFy commented
/e2e --refs substra-backend=feat/remove-parent_task_key --tests sdk,frontend --mode standalone

2023-01-02 15:36 UTC, Owlfred commented
End to end tests: :hourglass_flowing_sand: **STARTING**

2023-01-02 16:43 UTC, ThibaultFy approved these changes
Thanks !!

2023-01-02 16:43 UTC, ThibaultFy commented on CHANGELOG.md
> +- field `parent_task_keys` in `ComputeTask`
Put the PR number

2023-01-02 16:43 UTC, ThibaultFy commented on lib/service/computetaskstate.go
> +	for _, parentKey := range GetParentTaskKeys(child.Inputs) {
Might worth testing if it take too long for big inputs (with 1000 datasamples for instance)

2023-01-02 16:47 UTC, ThibaultFy commented
/e2e --refs substra-backend=feat/remove-parent_task_key --tests substrafl --mode standalone

2023-01-02 16:47 UTC, Owlfred commented
End to end tests: :hourglass_flowing_sand: **STARTING**

2023-01-02 16:47 UTC, ThibaultFy commented
/e2e --refs substra-backend=feat/remove-parent_task_key --tests NONE --mode standalone --benchmark mnist,camelyon

2023-01-02 16:47 UTC, Owlfred commented
Something happened while processing your message: error: unknown option '--benchmark'
(Did you mean --benchmarks?)

2023-01-02 16:48 UTC, ThibaultFy commented
/e2e --refs substra-backend=feat/remove-parent_task_key --tests NONE --mode standalone --benchmarks mnist,camelyon

2023-01-02 16:48 UTC, Owlfred commented
End to end tests: :hourglass_flowing_sand: **STARTING**

2023-01-03 08:00 UTC, ThibaultFy requested changes
E2E tests fail on SubstraFL and Benchmarks 😞

2023-01-03 08:00 UTC, ThibaultFy commented on lib/service/computetaskstate.go
> +	for _, parentKey := range GetParentTaskKeys(child.Inputs) {
The e2e failes on SubstraFL and Benchmarks, seems to be because of a timeout error....

2023-01-03 08:20 UTC, ThibaultFy commented
> End to end tests: ❌ [**FAILURE**](https://github.com/owkin/substra-ci/actions/runs/3823984016)
> 
> Jobs status:
> 
> * Tests Benchmark: [**❌**](https://github.com/owkin/substra-ci/actions/runs/3823984016/jobs/6505714234)
> * Tests Distributed: [**⏭️**](https://github.com/owkin/substra-ci/actions/runs/3823984016/jobs/6505714432)
> * Tests Standalone: [**✔️**](https://github.com/owkin/substra-ci/actions/runs/3823984016/jobs/6505714097)
> 
> Epic fail.

For the Mnist benchmark, the performances are impacted:
Expected: [0.8118, 0.7792, 0.9042, 0.8814, 0.9176, 0.9348, 0.9434, 0.9456, 0.9564, 0.9556]
Actual perf: [0.8118, 0.7792, 0.8388, 0.788, 0.869, 0.797, 0.8556, 0.8084, 0.866, 0.819]

2023-01-03 17:06 UTC, guilhem-barthes commented
/e2e --refs substra-backend=feat/remove-parent_task_key --tests sdk,substrafl,frontend --benchmarks mnist,camelyon

2023-01-03 17:06 UTC, Owlfred commented
End to end tests: :hourglass_flowing_sand: **STARTING**

2023-01-09 10:53 UTC, ThibaultFy approved these changes
Nice fix, can't wait to see it in action ;)

2023-01-09 10:53 UTC, ThibaultFy commented on CHANGELOG.md
> +- view `expanded_compute_tasks` ([#112](https://github.com/Substra/orchestrator/pull/112))
You can just put #112, github does the link to the PR automatically :)

2023-01-09 10:53 UTC, ThibaultFy commented on lib/service/computetaskstate.go
> +	err = s.applyTaskAction(child, transitionTodo, fmt.Sprintf("Last parent task %s done", triggeringParent.Key))
For my info: why remove the ":" here ?

2023-01-09 11:07 UTC, merged