rename algo to function
Substra/orchestrator pull request #139
Opened 2023-01-31 09:03 UTC by ThibaultFy

Signed-off-by: ThibaultFy <50656860+ThibaultFy@users.noreply.github.com>

## Description

## How has this been tested?

## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

2023-02-01 10:41 UTC, guilhem-barthes commented on server/standalone/migration/000055_rename-algo-to-function.up.sql
> +SET asset = asset - 'algo' || JSONB_BUILD_OBJECT('function', asset->'algo')
Make sure what was the field name before, the test failing seems to indicate that it was `algorithm` and not `algo`

2023-02-01 10:43 UTC, ThibaultFy commented on server/standalone/migration/000055_rename-algo-to-function.up.sql
> +SET asset = asset - 'algo' || JSONB_BUILD_OBJECT('function', asset->'algo')
It is on the migration 000029, it seems to be `algo`:/

2023-02-10 11:02 UTC, guilhem-barthes commented on docs/schemas/entities.mmd
> +    Function {}
Do we still need this line?

2023-02-10 11:04 UTC, guilhem-barthes commented on e2e/client/client.go
> +	functionService          asset.FunctionServiceClient
Can you please align the right column with the other ones?
```suggestion
	functionService      asset.FunctionServiceClient
```

2023-02-10 11:05 UTC, guilhem-barthes commented on e2e/client/client.go
> +		functionService:          asset.NewFunctionServiceClient(f.conn),
Same alignment here
```suggestion
		functionService:      asset.NewFunctionServiceClient(f.conn),
```

2023-02-10 11:15 UTC, guilhem-barthes requested changes
Thanks for this great job! I would just like to have `go fmt` on the full codebase (https://go.dev/blog/gofmt) and a small change on the migration

2023-02-10 11:15 UTC, guilhem-barthes commented on e2e/client/option.go
> +	FunctionRef        string
```suggestion
	FunctionRef    string
```

2023-02-10 11:15 UTC, guilhem-barthes commented on e2e/client/option.go
> +	FunctionRef        string
```suggestion
	FunctionRef    string
```

2023-02-10 11:15 UTC, guilhem-barthes commented on e2e/client/option.go
> +	FunctionRef        string
```suggestion
	FunctionRef    string
```

2023-02-10 11:15 UTC, guilhem-barthes commented on e2e/client/option.go
> +	FunctionRef        string
```suggestion
	FunctionRef    string
```

2023-02-10 11:15 UTC, guilhem-barthes commented on e2e/client/option.go
>  	Inputs  []*TaskInputOptions
In this case, align all the `string` to the furthest on the right

2023-02-10 11:15 UTC, guilhem-barthes commented on e2e/client/option.go
> +		FunctionRef:        DefaultMetricFunctionRef,
```suggestion
		FunctionRef:    DefaultMetricFunctionRef,
```

2023-02-10 11:15 UTC, guilhem-barthes commented on e2e/client/option.go
> +		FunctionKey:        ks.GetKey(o.FunctionRef),
```suggestion
		FunctionKey:    ks.GetKey(o.FunctionRef),
```

2023-02-10 11:15 UTC, guilhem-barthes commented on e2e/client/option.go
> +		FunctionRef:        DefaultSimpleFunctionRef,
```suggestion
		FunctionRef:    DefaultSimpleFunctionRef,
```

2023-02-10 11:15 UTC, guilhem-barthes commented on e2e/client/option.go
> +		FunctionKey:        ks.GetKey(o.FunctionRef),
```suggestion
		FunctionKey:    ks.GetKey(o.FunctionRef),
```

2023-02-10 11:15 UTC, guilhem-barthes commented on e2e/client/option.go
> +		FunctionRef:        DefaultPredictFunctionRef,
```suggestion
		FunctionRef:    DefaultPredictFunctionRef,
```

2023-02-10 11:15 UTC, guilhem-barthes commented on e2e/client/option.go
> +		FunctionKey:        ks.GetKey(o.FunctionRef),
```suggestion
		FunctionKey:    ks.GetKey(o.FunctionRef),
```

2023-02-10 11:15 UTC, guilhem-barthes commented on server/standalone/migration/000055_rename-algo-to-function.up.sql
> +WHERE asset_kind = 'ASSET_FUNCTION';
Can you please add a condition around this full migration to avoid to rerun it from a dirty state?

2023-02-10 11:16 UTC, ThibaultFy commented on server/standalone/migration/000055_rename-algo-to-function.up.sql
> +WHERE asset_kind = 'ASSET_FUNCTION';
Ah yes I wanted to do that... How do we choose the right condition ?

2023-02-10 12:29 UTC, guilhem-barthes commented on server/standalone/migration/000055_rename-algo-to-function.up.sql
> +RENAME COLUMN algorithm TO functionAddress;
Shouldn't it be function-address?

2023-02-10 12:30 UTC, guilhem-barthes commented on server/standalone/migration/000055_rename-algo-to-function.up.sql
> +        functionAddress          AS function_address,
shouldn't it be `function_address` ?

2023-02-10 12:30 UTC, guilhem-barthes commented on server/standalone/migration/000055_rename-algo-to-function.up.sql
> +	    permissions,
```suggestion
	permissions,
```

2023-02-10 12:33 UTC, guilhem-barthes commented on server/standalone/migration/000055_rename-algo-to-function.up.sql
> +WHERE asset_kind = 'ASSET_FUNCTION';
Mh ... That's a tricky one, we don't have guideliens on it but as everything should be executed in the same transaction, any of the changes can be used, for instance `table_exists('public', 'functions')`

2023-02-10 13:05 UTC, ThibaultFy commented on server/standalone/migration/000055_rename-algo-to-function.up.sql
> +RENAME COLUMN algorithm TO functionAddress;
I remember having an error using "_" in the name

2023-02-10 13:15 UTC, ThibaultFy commented on server/standalone/migration/000055_rename-algo-to-function.up.sql
> +WHERE asset_kind = 'ASSET_FUNCTION';
Do you mean `table_exists('public', 'algos')` ?

2023-02-10 16:38 UTC, merged